### ISSUE TITLE
Cancer

### ISSUE THREAD

**Issue by ghost** [KyleHunter/Java-Class-Updater#12]
[https://github.com/KyleHunter/Java-Class-Updater/blob/master/src/main/java/eUpdater/searchers/mutltiplierSearcher.java#L17](https://github.com/KyleHunter/Java-Class-Updater/blob/master/src/main/java/eUpdater/searchers/mutltiplierSearcher.java#L17)

Jesus fucking christ man. Take some pride in your code.

**Comment by KyleHunter** [comment]
Thanks for the feedback! :)
