### ISSUE TITLE
Deob failing on Ubuntu 16.04

### ISSUE THREAD

**Issue by Tape** [KyleHunter/Java-Class-Updater#6]
There seems to be an issue running the deob running on Ubuntu specifically, I have no issues with OSX. I'll take a look into it myself, just opening an issue to raise awareness.

Output:

```
GamePack downloading..
Beginning Deob..
Removed 0 Dummy Methods (0.06 ms)
Reordered 0 Multiplier Instructions (0.04 ms)
Reordered 0 Arithmetic Statements (0.48 ms)
Removed 0 Exceptions (0.04 ms)
Removed 0 Opaque Predicates (0.04 ms)
Removed 0 Dummy Parameters (0.03 ms)
Total Deob took 0.68 ms
Deob Finished..

0 Classes Found 

%% Identifying Classes..
null broke :/
null = 
```

**Comment by KyleHunter** [comment]
Depending on if you're on the latest version or not, i'm pretty sure it has to do with the way in which it creates the folders to hold the gamepack. Dunno how it would be different on linux but I assume that's the problem and if you manually create the folders it will probably work.

**Comment by Tape** [comment]
You were pretty close, it was a case sensitivity issue. I'll put in a PR.
